name: manual PR test
on:
  issue_comment:
    types: [created]

jobs:
  test-manual:
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '[test]')
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.7
          - 2.6
        gemfile:
          - Gemfile.rails42
          - Gemfile.rails52 # Min ruby 2.2.2
          - Gemfile.rails60 # Min ruby 2.5.0
          - Gemfile.rails61 # Min ruby 2.5.0
        exclude:
        - gemfile: Gemfile.rails42
          ruby: 2.7
        - gemfile: Gemfile.rails52
          ruby: 2.7

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rspec
